channels:
  - conda-forge
dependencies:
  - python=3.9.1
  - pip:
     - absl-py
     - adagio 
     - adal 
     - aiosignal 
     - ale-py 
     - alembic 
     - aniso8601 
     - antlr4-python3-runtime 
     - anyio 
     - appdirs 
     - applicationinsights 
     - appnope 
     - argcomplete 
     - argon2-cffi 
     - argon2-cffi-bindings 
     - arrow 
     - asttokens 
     - astunparse 
     - async-lru 
     - attrs 
     - AutoROM 
     - AutoROM.accept-rom-license 
     - azure-ai-ml 
     - azure-common 
     - azure-core 
     - azure-graphrbac 
     - azure-identity 
     - azure-mgmt-authorization 
     - azure-mgmt-containerregistry 
     - azure-mgmt-core 
     - azure-mgmt-keyvault 
     - azure-mgmt-network 
     - azure-mgmt-resource 
     - azure-mgmt-storage 
     - azure-storage-blob 
     - azure-storage-file-datalake 
     - azure-storage-file-share 
     - azureml 
     - azureml-core 
     - azureml-telemetry 
     - azureml-tensorboard 
     - azureml-widgets 
     - Babel 
     - backcall 
     - backports.tempfile 
     - backports.weakref 
     - bcrypt 
     - beautifulsoup4 
     - bleach 
     - blinker 
     - cachetools 
     - certifi 
     - cffi 
     - charset-normalizer 
     - click 
     - cloudpickle 
     - colorama 
     - comm 
     - contextlib2 
     - contourpy 
     - cryptography 
     - cycler 
     - debugpy 
     - decorator 
     - defusedxml 
     - dm-tree 
     - docker 
     - docopt 
     - dos2unix 
     - entrypoints 
     - exceptiongroup 
     - executing 
     - Farama-Notifications 
     - fastjsonschema 
     - filelock 
     - Flask 
     - flatbuffers 
     - fonttools 
     - fqdn 
     - frozenlist 
     - fs 
     - fsspec 
     - fugue 
     - fugue-sql-antlr 
     - gast 
     - gitdb 
     - GitPython 
     - google-api-core 
     - google-auth 
     - google-auth-oauthlib 
     - google-pasta 
     - googleapis-common-protos 
     - GPUtil 
     - graphene 
     - graphql-core 
     - graphql-relay 
     - grpcio 
     - gunicorn 
     - gym 
     - gym-notices 
     - gymnasium 
     - h5py 
     - humanfriendly 
     - idna 
     - imageio 
     - importlib-metadata 
     - importlib-resources 
     - ipykernel 
     - ipython 
     - ipython-genutils 
     - ipywidgets 
     - isodate 
     - isoduration 
     - itsdangerous 
     - jax-jumpy 
     - jedi 
     - jeepney 
     - Jinja2 
     - jmespath 
     - joblib 
     - json5 
     - jsonpickle 
     - jsonpointer 
     - jsonschema 
     - jsonschema-specifications 
     - jupyter-events 
     - jupyter-lsp 
     - jupyter_client 
     - jupyter_core 
     - jupyter_server 
     - jupyter_server_terminals 
     - jupyterlab 
     - jupyterlab-pygments 
     - jupyterlab_server 
     - jupyterlab_widgets 
     - keras 
     - kiwisolver 
     - knack 
     - lazy_loader 
     - libclang 
     - lz4 
     - Mako 
     - Markdown 
     - markdown-it-py 
     - MarkupSafe 
     - marshmallow 
     - matplotlib 
     - matplotlib-inline 
     - mdurl 
     - mistune 
     - ml-dtypes 
     - mlflow 
     - MouseInfo 
     - mpmath 
     - msal 
     - msal-extensions 
     - msgpack 
     - msrest 
     - msrestazure 
     - nbclient 
     - nbconvert 
     - nbformat 
     - ndg-httpsclient 
     - nest-asyncio 
     - networkx 
     - notebook 
     - notebook_shim 
     - numpy 
     - oauthlib 
     - opencensus 
     - opencensus-context 
     - opencensus-ext-azure 
     - opencensus-ext-logging 
     - opencv-python 
     - opt-einsum 
     - overrides 
     - packaging 
     - pandas 
     - pandocfilters 
     - paramiko 
     - parso 
     - pathspec 
     - pettingzoo 
     - pexpect 
     - pfrl 
     - pickleshare 
     - Pillow 
     - pipreqs 
     - pkginfo 
     - platformdirs 
     - portalocker 
     - prometheus-client 
     - prompt-toolkit 
     - proto-plus 
     - protobuf 
     - psutil 
     - ptyprocess 
     - pure-eval 
     - py-spy 
     - pyarrow 
     - pyasn1 
     - pyasn1-modules 
     - PyAutoGUI 
     - pycparser 
     - pydash 
     - pygame 
     - PyGetWindow 
     - Pygments 
     - PyJWT 
     - PyMsgBox 
     - PyNaCl 
      # pyobjc-core 
      # pyobjc-framework-Cocoa 
      # pyobjc-framework-Quartz 
     - pyOpenSSL 
     - pyparsing 
     - pyperclip 
     - PyRect 
     - PyScreeze 
     - PySocks 
     - python-dateutil 
     - python-json-logger 
     - pytweening 
     - pytz 
     - PyYAML 
     - pyzmq 
     - qpd 
     - querystring-parser 
     - ray==2.8.0
     - ray-on-aml 
     - referencing 
     - requests 
     - requests-oauthlib 
     - rfc3339-validator 
     - rfc3986-validator 
     - rich 
     - rpds-py 
     - rsa 
     - rubicon-objc 
     - scikit-image 
     - scikit-learn 
     - scipy 
     - SecretStorage 
     - Send2Trash 
     - Shimmy 
     - six 
     - smmap 
     - sniffio 
     - soupsieve 
     - SQLAlchemy 
     - sqlglot 
     - sqlparse 
     - stable-baselines3 
     - stack-data 
     - strictyaml 
     - sumo-rl 
     - sumolib 
     - SuperSuit 
     - sympy 
     - tabulate 
     - tensorboard 
     - tensorboard-data-server 
     - tensorboardX 
     - tensorflow==2.14.0
     - tensorflow-estimator 
     - tensorflow-io-gcs-filesystem 
     - termcolor 
     - terminado 
     - threadpoolctl 
     - tifffile 
     - tinycss2 
     - tinyscaler 
     - tomli 
     - torch 
     - torch-tb-profiler 
     - torchaudio 
     - torchsummary 
     - torchvision 
     - tornado 
     - tqdm 
     - traci 
     - traitlets 
     - triad 
     - tune 
     - typer 
     - types-python-dateutil 
     - typing_extensions 
     - tzdata 
     - uri-template 
     - urllib3 
     - wcwidth 
     - webcolors 
     - webencodings 
     - websocket-client 
     - Werkzeug 
     - widgetsnbextension 
     - wrapt 
     - xorg-libx11
     - yarg 
     - zipp 
  - pip < 23.3.1